apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-server-b
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes: 
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-mods-server-b
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup-server-b
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 20Gi
volumeName: pvc-95b89f72-759e-4247-a567-8b1b32e7b332
  accessModes: 
  - ReadWriteMany