apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes: 
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup
spec:
  resources:
    requests:
      storage: 20Gi
  accessModes: 
  - ReadWriteOnce