apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-server-a
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes: 
  - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-plugins-server-a
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 1Gi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-backup-server-a
spec:
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 20Gi
  accessModes: 
  - ReadWriteMany